apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: not-alone
  name: not-alone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: not-alone
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: not-alone
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}